### ISSUE TITLE
issues about BLEU

### ISSUE THREAD

**Issue by SkipAngel** [wenhuchen/Data-to-text-Evaluation-Metric#1]
Running MTEval to compute BLEU & NIST...
Traceback (most recent call last):
  File "./measure_scores.py", line 347, in <module>
    evaluate(data_src, data_ref, data_sys, args.table, args.header, args.sys_file, args.python)
  File "./measure_scores.py", line 208, in evaluate
    mteval_scores = run_mteval(data_ref, data_sys, data_src)
  File "./measure_scores.py", line 247, in run_mteval
    '-f', mteval_log_file], stderr=subprocess.STDOUT)
  File "/home/xushoukai/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/xushoukai/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['perl', '/home/xushoukai/KGPT-webnlg/Data-to-text-Evaluation-Metric/mteval/mteval-v13a-sig.pl', '-r', '/tmp/e2e-eval-dadl3uut/mteval_ref.sgm', '-s', '/tmp/e2e-eval-dadl3uut/mteval_src.sgm', '-t', '/tmp/e2e-eval-dadl3uut/mteval_sys.sgm', '-f', '/tmp/e2e-eval-dadl3uut/mteval_log.txt']' returned non-zero exit status 2.
We don't change the code. I have no idea.

**Comment by wenhuchen** [comment]
Hi, did you install the library like
"""
curl -L https://cpanmin.us | perl - App::cpanminus  # install cpanm
cpanm XML::Twig
"""

**Comment by SkipAngel** [comment]
I installed the library.Successfully installed XML-Twig-3.52

**Comment by wenhuchen** [comment]
You can directly type in the command implied by the following into the terminal to debug.
"""
['perl', '/home/xushoukai/KGPT-webnlg/Data-to-text-Evaluation-Metric/mteval/mteval-v13a-sig.pl', '-r', '/tmp/e2e-eval-dadl3uut/mteval_ref.sgm', '-s', '/tmp/e2e-eval-dadl3uut/mteval_src.sgm', '-t', '/tmp/e2e-eval-dadl3uut/mteval_sys.sgm', '-f', '/tmp/e2e-eval-dadl3uut/mteval_log.txt']'
"""
I suspect you missed some library or your Perl is not working well.

**Comment by SkipAngel** [comment]
thanks
